name: CI

on:
  push:
  pull_request:
  
permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install pytest
        run: pip install pytest -r requirements.txt

      - name: build
        run: pytest -m compileall .
test:
  needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install pytest -r requirements.txt
        run: pip install pytest

      - name: Run tests
        run: pytest
      
